project_id = "qclaciklevavttipztrv"

[functions.auth-email-hook]
verify_jwt = false

[functions.serve-event-asset]
verify_jwt = false

[functions.confirm-rsvp]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = false

[functions.paypal-capture-order]
verify_jwt = false

[functions.paypal-create-subscription]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.survey-api]
verify_jwt = false

[functions.send-survey-links]
verify_jwt = false
