project_id = "agfsnvywlltiiigkatar"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
  [functions.confirm-rsvp]
    verify_jwt = false
  [functions.send-communication]
    verify_jwt = false
