// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ── Startup guard ──────────────────────────────────────────────
if (!SUPABASE_URL) {
  console.error(
    `[TitanMeet] ⚠️  SUPABASE_URL is not set!\n` +
    `  Set VITE_SUPABASE_URL in your .env file.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ── Edge Function helpers ──────────────────────────────────────

// Functions ported to the local Express server
const LOCAL_FUNCTIONS = new Set([
  "check-plan-limits",
  "send-event-invitations",
  "validate-discount",
  "ai-assistant",
  "event-concierge",
]);

async function getAuthHeader(): Promise<string | undefined> {
  const { data: { session } } = await supabase.auth.getSession();
  return session?.access_token ? `Bearer ${session.access_token}` : undefined;
}

/**
 * Invoke an Edge Function — either via the local Express server (for ported
 * functions) or directly through Supabase (for remaining edge functions).
 */
export async function invokeEdgeFunction<T = unknown>(
  name: string,
  payload?: Record<string, unknown>,
): Promise<{ data: T | null; error: Error | null }> {
  if (LOCAL_FUNCTIONS.has(name)) {
    try {
      const authHeader = await getAuthHeader();
      const headers: Record<string, string> = { "Content-Type": "application/json" };
      if (authHeader) headers["Authorization"] = authHeader;
      const res = await fetch(`/api/functions/${name}`, {
        method: "POST",
        headers,
        body: JSON.stringify(payload ?? {}),
      });
      const data = await res.json();
      if (!res.ok) return { data: null, error: new Error(data?.error || `HTTP ${res.status}`) };
      return { data: data as T, error: null };
    } catch (err: any) {
      return { data: null, error: err };
    }
  }

  const { data, error } = await supabase.functions.invoke(name, {
    body: payload ?? {},
  });
  return { data: data as T | null, error };
}

/**
 * Build a full Edge Function URL and fetch it directly.
 * Use this for **unauthenticated / public** calls where
 * query-string params or non-JSON methods are needed.
 */
export function edgeFunctionUrl(name: string, query?: Record<string, string>): string {
  const base = `${SUPABASE_URL}/functions/v1/${name}`;
  if (!query) return base;
  const qs = new URLSearchParams(query).toString();
  return `${base}?${qs}`;
}
