// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ── Startup guard ──────────────────────────────────────────────
if (!SUPABASE_URL) {
  console.error(
    `[TitanMeet] ⚠️  SUPABASE_URL is not set!\n` +
    `  Set VITE_SUPABASE_URL in your .env file.`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ── Edge Function helpers ──────────────────────────────────────

/**
 * Invoke a Supabase Edge Function with the current user's JWT.
 * Use this for authenticated calls (most dashboard actions).
 */
export async function invokeEdgeFunction<T = unknown>(
  name: string,
  payload?: Record<string, unknown>,
): Promise<{ data: T | null; error: Error | null }> {
  const { data, error } = await supabase.functions.invoke(name, {
    body: payload ?? {},
  });
  return { data: data as T | null, error };
}

/**
 * Build a full Edge Function URL and fetch it directly.
 * Use this for **unauthenticated / public** calls where
 * query-string params or non-JSON methods are needed.
 */
export function edgeFunctionUrl(name: string, query?: Record<string, string>): string {
  const base = `${SUPABASE_URL}/functions/v1/${name}`;
  if (!query) return base;
  const qs = new URLSearchParams(query).toString();
  return `${base}?${qs}`;
}
